apiVersion: apps/v1
kind: Deployment
metadata:
  name: petstore
spec:
  selector:
    matchLabels:
      app: petstore
  replicas: 1 
  template: 
    metadata:
      labels:
        app: petstore
    spec:
      containers:
      - name: petshop
        image: mukeshr29/petstore:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: petstore
spec:
  type: LoadBalancer
  selector:
    app: petstore  # Match the labels used in the Deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
