---
- name: Deploy Kubernetes Application
  hosts: k8s
  gather_facts: yes

  tasks:
    - name: Copy deployment.yaml to Kubernetes master
      copy:
        src: /var/lib/jenkins/workspace/project-2.2/deployment.yaml
        dest: /home/ubuntu/
      become: yes
      become_user: root

    - name: Apply Deployment
      k8s:
        state: present
        definition: /home/ubuntu/deployment.yaml
        kubeconfig: /home/ubuntu/.kube/config
