- name: Stop and remove existing container
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Stop and remove existing container
      docker_container:
        name: pet1
        state: absent
      ignore_errors: yes

- name: Deploy Kubernetes Application
  hosts: k8s
  gather_facts: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Copy deployment.yaml to Kubernetes master
      copy:
        src: /var/lib/jenkins/workspace/project-2.2/deployment.yaml
        dest: /home/ubuntu/
      become: yes
      become_user: root

    - name: Apply Deployment using kubectl
      command: kubectl apply -f /home/ubuntu/deployment.yaml
      args:
        chdir: /home/ubuntu/
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config
