---
- name: Deploy Kubernetes Application
  hosts: k8s
  gather_facts: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_python_interpreter_openshift: /usr/bin/python3

  tasks:
    - name: Copy deployment.yaml to Kubernetes master
      copy:
        src: /var/lib/jenkins/workspace/project-2.2/deployment.yaml
        dest: /home/ubuntu/
      become: yes
      become_user: root

    - name: Apply Deployment using openshift module
      openshift:
        state: present
        definition: /home/ubuntu/deployment.yaml
        kubeconfig: /home/ubuntu/.kube/config
